
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:24:36 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'constraint.ucf'
####################################################################################

#$Id: red_pitaya.ucf 961 2014-01-21 11:40:39Z matej.oblak $
#
# @brief Red Pitaya location constraints.
#
# @Author Matej Oblak
#
# (c) Red Pitaya  http://www.redpitaya.com
#


############################################################################
# Clock constraints                                                        #
############################################################################

set_property PACKAGE_PIN U18 [get_ports clk]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'clk' has been applied to the port object 'clk'.
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:17
create_clock -name clk -period 30.303 [get_ports clk]




### Expansion connector
set_property PACKAGE_PIN G17 [get_ports din]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:23
# The conversion of 'IOSTANDARD' constraint on 'net' object 'din' has been applied to the port object 'din'.
set_property IOSTANDARD LVCMOS33 [get_ports din]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:23
# The conversion of 'DRIVE' constraint on 'net' object 'din' has been applied to the port object 'din'.
set_property DRIVE 8 [get_ports din]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:23
# The conversion of 'SLEW' constraint on 'net' object 'din' has been applied to the port object 'din'.
set_property SLEW FAST [get_ports din]
set_property PACKAGE_PIN G18 [get_ports {z[0]}]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:24
# The conversion of 'IOSTANDARD' constraint on 'net' object 'z[0]' has been applied to the port object 'z[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {z[0]}]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:24
# The conversion of 'DRIVE' constraint on 'net' object 'z[0]' has been applied to the port object 'z[0]'.
set_property DRIVE 8 [get_ports {z[0]}]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:24
# The conversion of 'SLEW' constraint on 'net' object 'z[0]' has been applied to the port object 'z[0]'.
set_property SLEW FAST [get_ports {z[0]}]
set_property PACKAGE_PIN H16 [get_ports {z[1]}]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'z[1]' has been applied to the port object 'z[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {z[1]}]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:25
# The conversion of 'DRIVE' constraint on 'net' object 'z[1]' has been applied to the port object 'z[1]'.
set_property DRIVE 8 [get_ports {z[1]}]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:25
# The conversion of 'SLEW' constraint on 'net' object 'z[1]' has been applied to the port object 'z[1]'.
set_property SLEW FAST [get_ports {z[1]}]
set_property PACKAGE_PIN H17 [get_ports valid_in]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:26
# The conversion of 'IOSTANDARD' constraint on 'net' object 'valid_in' has been applied to the port object 'valid_in'.
set_property IOSTANDARD LVCMOS33 [get_ports valid_in]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:26
# The conversion of 'DRIVE' constraint on 'net' object 'valid_in' has been applied to the port object 'valid_in'.
set_property DRIVE 8 [get_ports valid_in]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:26
# The conversion of 'SLEW' constraint on 'net' object 'valid_in' has been applied to the port object 'valid_in'.
set_property SLEW FAST [get_ports valid_in]
set_property PACKAGE_PIN J18 [get_ports valid_out]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:27
# The conversion of 'IOSTANDARD' constraint on 'net' object 'valid_out' has been applied to the port object 'valid_out'.
set_property IOSTANDARD LVCMOS33 [get_ports valid_out]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:27
# The conversion of 'DRIVE' constraint on 'net' object 'valid_out' has been applied to the port object 'valid_out'.
set_property DRIVE 8 [get_ports valid_out]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:27
# The conversion of 'SLEW' constraint on 'net' object 'valid_out' has been applied to the port object 'valid_out'.
set_property SLEW FAST [get_ports valid_out]
set_property PACKAGE_PIN H18 [get_ports reset]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:28
# The conversion of 'IOSTANDARD' constraint on 'net' object 'reset' has been applied to the port object 'reset'.
set_property IOSTANDARD LVCMOS33 [get_ports reset]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:28
# The conversion of 'DRIVE' constraint on 'net' object 'reset' has been applied to the port object 'reset'.
set_property DRIVE 8 [get_ports reset]
# /home/amar/VHDL_CHCODING/ConvCodingI/constraint.ucf:28
# The conversion of 'SLEW' constraint on 'net' object 'reset' has been applied to the port object 'reset'.
set_property SLEW FAST [get_ports reset]


